/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intercode;

import java.io.DataOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.border.EmptyBorder;
import org.fife.ui.rtextarea.*;
import org.fife.ui.rsyntaxtextarea.*;
import java.io.Serializable;
import static java.lang.Thread.sleep;
/**
 *
 * @author amank
 */
public class Coding extends javax.swing.JFrame{
    
   private JTextField searchField;
   private JCheckBox regexCB;
   private JCheckBox matchCaseCB;
   Font fontc;
    /**
     * Creates new form Coding
     */
    
    static RSyntaxTextArea textArea = new RSyntaxTextArea(19, 62);
    
    public Coding() {
      
        //fontdialog=new FontSelect(this);
      JPanel cp = new JPanel(new BorderLayout());
      cp.setBorder(new EmptyBorder(80,490,10,10));
      textArea.setBounds(400,100,700 ,220);
      Font font = new Font("Monospaced", Font.PLAIN, 18);
        textArea.setFont(font);
       textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVA);
      textArea.setCodeFoldingEnabled(true);
      RTextScrollPane sp = new RTextScrollPane(textArea);
      cp.add(sp);
        System.out.println("2");
      setContentPane(cp);
      setTitle("Text Editor ");
      setDefaultCloseOperation(EXIT_ON_CLOSE);
      pack();
      setLocationRelativeTo(null);
        
        initComponents();
        
    }
    
    
    static boolean state = true;
    static int milliseconds = 0;
    static int seconds = 0;
    static int minutes = 0;
    static int hours = 0;
    
    static int x =0;
    
    
    
    
    static  
    {
        
        Start st = new Start();
        st.setVisible(true);
        
    }
    
    
    /*
    
    //-------------------old code before adding start java ----------------
    static 
    {
        Login_form log = new Login_form();
        log.setVisible(true);
        
    }

*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane6 = new javax.swing.JScrollPane();
        ques_area1 = new javax.swing.JTextArea();
        qsend1 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        ans_area1 = new javax.swing.JTextArea();
        lang1 = new javax.swing.JComboBox<>();
        Run1 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        Output1 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        input1 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        msg_area1 = new javax.swing.JTextArea();
        msg_field1 = new javax.swing.JTextField();
        msg_send1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        font1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        ques_area = new javax.swing.JTextArea();
        qsend = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ans_area = new javax.swing.JTextArea();
        lang = new javax.swing.JComboBox<>();
        Run = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        Output = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        input = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        msg_area = new javax.swing.JTextArea();
        msg_field = new javax.swing.JTextField();
        msg_send = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        hour = new javax.swing.JLabel();
        minute = new javax.swing.JLabel();
        second = new javax.swing.JLabel();
        millisecond = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        font = new javax.swing.JMenuItem();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ques_area1.setColumns(20);
        ques_area1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        ques_area1.setRows(5);
        ques_area1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ques_area1KeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(ques_area1);

        jFrame1.getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 410, 200));

        qsend1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        qsend1.setForeground(new java.awt.Color(133, 16, 32));
        qsend1.setText("Send");
        qsend1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 204), 3, true));
        qsend1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qsend1ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(qsend1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 130, 40));

        ans_area1.setColumns(20);
        ans_area1.setRows(5);
        ans_area1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ans_area1KeyPressed(evt);
            }
        });
        jScrollPane7.setViewportView(ans_area1);

        jFrame1.getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 400, 190));

        lang1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lang1.setForeground(new java.awt.Color(131, 21, 21));
        lang1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "C++", "JAVA", "PYTH" }));
        jFrame1.getContentPane().add(lang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 610, 140, 40));

        Run1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Run1.setForeground(new java.awt.Color(136, 14, 14));
        Run1.setText("RUN");
        Run1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 204), 3, true));
        Run1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Run1ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(Run1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 610, 130, 40));

        Output1.setColumns(20);
        Output1.setRows(5);
        jScrollPane8.setViewportView(Output1);

        jFrame1.getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 670, 630, 180));

        input1.setColumns(20);
        input1.setRows(5);
        jScrollPane9.setViewportView(input1);

        jFrame1.getContentPane().add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 420, 160));

        msg_area1.setColumns(20);
        msg_area1.setRows(5);
        jScrollPane10.setViewportView(msg_area1);

        jFrame1.getContentPane().add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 160, 350, 390));
        jFrame1.getContentPane().add(msg_field1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 650, 320, 70));

        msg_send1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        msg_send1.setForeground(new java.awt.Color(131, 16, 16));
        msg_send1.setText("Send");
        msg_send1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 204), 3, true));
        msg_send1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_send1ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(msg_send1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 750, 120, 36));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 3, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 153));
        jLabel8.setText("Write Text");
        jFrame1.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 590, 160, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 45)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 153));
        jLabel9.setText("Coding Area");
        jFrame1.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 320, 60));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 3, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 255, 153));
        jLabel10.setText("Ques Area");
        jFrame1.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 280, 40));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 3, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 255, 153));
        jLabel11.setText("Ans Area");
        jFrame1.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 250, 40));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 3, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 255, 153));
        jLabel12.setText("Input");
        jFrame1.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 180, 40));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 3, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 255, 153));
        jLabel13.setText("Output");
        jFrame1.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 610, 150, 40));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 3, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 255, 153));
        jLabel14.setText("Chat Area");
        jFrame1.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 90, 150, 40));

        background1.setBackground(new java.awt.Color(102, 204, 255));
        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intercode/dell-background.jpg"))); // NOI18N
        jFrame1.getContentPane().add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1670, 870));

        jMenuBar2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenu4.setText("File");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Save Data");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem5.setText("Fetch Data");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem6.setText("Find");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        font1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        font1.setText("Font");
        font1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                font1ActionPerformed(evt);
            }
        });
        jMenu5.add(font1);

        jMenuBar2.add(jMenu5);

        jMenu6.setText("Chat");
        jMenuBar2.add(jMenu6);

        jFrame1.setJMenuBar(jMenuBar2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(50, 50, 600, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ques_area.setColumns(20);
        ques_area.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        ques_area.setRows(5);
        ques_area.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ques_areaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(ques_area);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 410, 200));

        qsend.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        qsend.setForeground(new java.awt.Color(133, 16, 32));
        qsend.setText("Send");
        qsend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 204), 3, true));
        qsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qsendActionPerformed(evt);
            }
        });
        getContentPane().add(qsend, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 130, 40));

        ans_area.setEditable(false);
        ans_area.setColumns(20);
        ans_area.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        ans_area.setRows(5);
        ans_area.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ans_areaKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(ans_area);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 400, 190));

        lang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lang.setForeground(new java.awt.Color(131, 21, 21));
        lang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "C++", "JAVA", "PYTH" }));
        getContentPane().add(lang, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 610, 140, 40));

        Run.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Run.setForeground(new java.awt.Color(136, 14, 14));
        Run.setText("RUN");
        Run.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 204), 3, true));
        Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunActionPerformed(evt);
            }
        });
        getContentPane().add(Run, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 610, 130, 40));

        Output.setColumns(20);
        Output.setRows(5);
        jScrollPane4.setViewportView(Output);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 670, 630, 180));

        input.setColumns(20);
        input.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        input.setRows(5);
        jScrollPane5.setViewportView(input);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 420, 160));

        msg_area.setEditable(false);
        msg_area.setColumns(20);
        msg_area.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        msg_area.setRows(5);
        jScrollPane3.setViewportView(msg_area);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 160, 350, 390));

        msg_field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(msg_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 620, 320, 70));

        msg_send.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        msg_send.setForeground(new java.awt.Color(131, 16, 16));
        msg_send.setText("Send");
        msg_send.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 204), 3, true));
        msg_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_sendActionPerformed(evt);
            }
        });
        getContentPane().add(msg_send, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 710, 120, 36));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("Write Text");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 570, 160, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 42)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setText("Coding Area");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 320, 60));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 153));
        jLabel3.setText("Ques Area");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 280, 40));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 153));
        jLabel4.setText("Ans Area");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 250, 40));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 153));
        jLabel5.setText("Input");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 180, 40));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 3, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 153));
        jLabel6.setText("Output");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 610, 150, 40));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 3, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 153));
        jLabel7.setText("Chat Area");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 90, 150, 40));

        clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(131, 16, 16));
        clear.setText("Clear Output");
        clear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 204), 3, true));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 810, 150, 36));

        hour.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hour.setForeground(new java.awt.Color(255, 255, 255));
        hour.setText("00 :");
        getContentPane().add(hour, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 20, 70, 50));

        minute.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        minute.setForeground(new java.awt.Color(255, 255, 255));
        minute.setText("00 :");
        getContentPane().add(minute, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 20, 70, 50));

        second.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        second.setForeground(new java.awt.Color(255, 255, 255));
        second.setText("00 :");
        getContentPane().add(second, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 20, 70, 50));

        millisecond.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        millisecond.setForeground(new java.awt.Color(255, 255, 255));
        millisecond.setText("00 ");
        getContentPane().add(millisecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 30, 50, 40));

        background.setBackground(new java.awt.Color(102, 204, 255));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intercode/dell-background.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1680, 880));

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenu1.setText("File");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem2.setText("Save Data");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem3.setText("Fetch Data");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem7.setText("Add Path");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem1.setText("Find");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        font.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        font.setText("Font");
        font.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontActionPerformed(evt);
            }
        });
        jMenu2.add(font);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ques_areaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ques_areaKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ques_areaKeyPressed

    private void qsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qsendActionPerformed
        // TODO add your handling code here:
          if(is_client_online()==1){
            
        try {
            
          
        Socket ques = Connect_Client_Login.getQues();
        
        OutputStream os = ques.getOutputStream();
        DataOutputStream dos = new DataOutputStream(os);
        
        String msg = ques_area.getText();
            dos.writeUTF(msg);
        } catch (Exception ex) {
            Logger.getLogger(Coding.class.getName()).log(Level.SEVERE, null, ex);
        } }
        
        else
          {
              JOptionPane.showMessageDialog(null,"Interviewee is offline,  So message can't be send. ");
              return;
          }
        
        
    }//GEN-LAST:event_qsendActionPerformed

    private void ans_areaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ans_areaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ans_areaKeyPressed

    private void msg_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_sendActionPerformed
        // TODO add your handling code here:
         if(is_client_online()==1){
        
        try {
            
            
        Socket u = Connect_Client_Login.getMsg();
        
        OutputStream os = u.getOutputStream();
        DataOutputStream dos = new DataOutputStream(os);
        
        String msg = msg_field.getText();
            dos.writeUTF(msg);
        } catch (Exception ex) {
            Logger.getLogger(Coding.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        else
          {
              JOptionPane.showMessageDialog(null,"Interviewee is offline, So message can't be send.    ");
              return;
          }
        
        
    }//GEN-LAST:event_msg_sendActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        
       FindAndReplace find = new FindAndReplace();
       find.setVisible(true);
           // demo.textArea.requestFocusInWindow();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    
     private void print(String status,InputStream input) throws IOException{
BufferedReader in = new BufferedReader(new InputStreamReader(input));
System.out.println("************* "+status+"***********************");
//TF.setText("************* "+status+"***********************");
String line = "",k,g;
do{k=Output.getText();

 System.out.println(line);

 Output.setText(k+"\n"+line);
}while((line = in.readLine()) != null );
in.close();
}
    
    
    
    private void RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunActionPerformed
        // TODO add your handling code here:
        
        String a = lang.getSelectedItem().toString();
          Thread t = new Thread(new Compile_Run(a));
          t.start();
        
        
    
        
    }//GEN-LAST:event_RunActionPerformed

    private void fontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontActionPerformed
        // TODO add your handling code here:
        Font_class fc = new Font_class();
        fc.setVisible(true);
        
       // Thread t = new Thread(new Set_Font());
       // t.start();
        
     
    }//GEN-LAST:event_fontActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        Rate ra = new Rate();
        ra.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        
        Fetch_Data fd = new Fetch_Data();
        fd.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void ques_area1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ques_area1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ques_area1KeyPressed

    private void qsend1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qsend1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qsend1ActionPerformed

    private void ans_area1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ans_area1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ans_area1KeyPressed

    private void Run1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Run1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Run1ActionPerformed

    private void msg_send1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_send1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msg_send1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void font1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_font1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_font1ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        
       Output.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       
        Path p = new Path();
        p.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    
    int is_client_online()
    {
        return x ;
    }
    
    
    
     static  Thread t = new Thread()
        {
          public void run()
          {
              for(;;)
              {
                  System.out.println("in timer for : class coding ");
                  
                  if(state==true)
                  {
                      try
                      {
                          sleep(1);
                          
                          if(milliseconds>1000)
                          {
                              milliseconds=0;
                              seconds++;
                          }
                          if(seconds>60)
                          {
                              milliseconds=0;
                              seconds=0;
                              minutes++;
                          }
                          if(minutes>60)
                          {
                              milliseconds=0;
                              seconds=0;
                              minutes=0;
                              hours++;
                          }
                          
                          millisecond.setText(""+milliseconds);
                          milliseconds++;
                          second.setText(""+seconds+" : ");
                          minute.setText(""+minutes+" : ");
                          hour.setText(""+hours+" : ");
                          
                          
                      }
                      catch(Exception e)
                      {
                          
                      }
                  }
                  else
                  {
                      break;
                  }
              }
          }
        };
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Coding().setVisible(true);
            }
        });
      
        while( true)
        {
            int x=Connect_Client_Login.getchceck();
          System.out.println(" ");
          
         if( x==1)   
         {  Socket s,u,v,w;
         
            s= Connect_Client_Login.getQues();
            System.out.println("in server"+s);
            Thread t1 = new Thread (new Receive_Ans(s));
            t1.start();
            
            u=Connect_Client_Login.getMsg();
            Thread t2 = new Thread(new Receive_Msg(u));
            t2.start();
            
            v = Connect_Client_Login.getCode();
             System.out.println("starting t3");
            Thread t3 = new Thread(new Receive_code(v));
            t3.start();
            
            
            
           
            
            
            break;
         }
        
        }
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea Output;
    public static javax.swing.JTextArea Output1;
    private javax.swing.JButton Run;
    private javax.swing.JButton Run1;
    public static javax.swing.JTextArea ans_area;
    public static javax.swing.JTextArea ans_area1;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JButton clear;
    private javax.swing.JMenuItem font;
    private javax.swing.JMenuItem font1;
    public static javax.swing.JLabel hour;
    public static javax.swing.JTextArea input;
    public static javax.swing.JTextArea input1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JComboBox<String> lang;
    public javax.swing.JComboBox<String> lang1;
    public static javax.swing.JLabel millisecond;
    public static javax.swing.JLabel minute;
    public static javax.swing.JTextArea msg_area;
    public static javax.swing.JTextArea msg_area1;
    public static javax.swing.JTextField msg_field;
    public static javax.swing.JTextField msg_field1;
    private javax.swing.JButton msg_send;
    private javax.swing.JButton msg_send1;
    private javax.swing.JButton qsend;
    private javax.swing.JButton qsend1;
    public static javax.swing.JTextArea ques_area;
    public static javax.swing.JTextArea ques_area1;
    public static javax.swing.JLabel second;
    // End of variables declaration//GEN-END:variables
}
