/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intercode;

/**
 *
 * @author amank
 */
public class Font_class extends javax.swing.JFrame {

    /**
     * Creates new form Font_class
     */
    
    static String size="";
    static String style="";
    static String font="";
    static int check=0;
    
    
    public Font_class() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        style_list = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        size_list = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        font_list = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Font");
        setBounds(new java.awt.Rectangle(600, 200, 70, 100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        style_list.setBackground(new java.awt.Color(204, 255, 204));
        style_list.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        style_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "PLAIN", "BOLD", "ITALIC", "BOLD ITALIC", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(style_list);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 110, 188));

        jScrollPane2.setBackground(new java.awt.Color(204, 255, 204));

        size_list.setBackground(new java.awt.Color(204, 255, 204));
        size_list.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        size_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "3", "5", "8", "10", "12", "14", "18", "24", "36", "48", "54", "60" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(size_list);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 98, 183));

        font_list.setBackground(new java.awt.Color(204, 255, 204));
        font_list.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        font_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Agency FB", "Algerian", "Aparajita", "Arial", "Arial Black", "Arial Narrow", "Arial Unicode MS", "Bell MT", "Berlin Sans FB", "Bernard MT Condensed", "Bodoni MT", "Chiller", "Colonna MT", "Consolas", "Constantia", "Cooper Black", "Gadugi", "Garamond", "Georgia", "Impact", "Ink Free", "Javanese Text", "Juice ITC", "Mangal", "Marlett", "Matura MT Script Capitals", "Meiryo", "Sylfaen", "Symbol", "Tahoma", "Tempus Sans ITC", "Times New Roman", "Trebuchet MS", "Tw Cen MT", "Yu Gothic ", "YU Gothic Light ", "Yu Gothic Semibold", "Yu Gothic  Semilight", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(font_list);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 218, 188));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Style :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 84, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Size : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 84, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Font :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 123, 30));

        ok.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 70, 37));

        cancel.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, -1, 37));

        jLabel4.setBackground(new java.awt.Color(255, 153, 153));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intercode/ak.jpeg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        
        size = size_list.getSelectedValue();
        style = style_list.getSelectedValue();
        font = font_list.getSelectedValue();
        //System.out.println(size);
        
        check =1;
        
         Thread t = new Thread(new Set_Font());
        t.start();
        
        
    }//GEN-LAST:event_okActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    static String getSize_value()
    {
        return size;
    }
    
    static String getStyle()
    {
        return style;
    }
    
    static String getFont_name()
    {
        return font;
    }
    
    static int ischeck()
    {
        return check;
    }
    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    public javax.swing.JList<String> font_list;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton ok;
    private javax.swing.JList<String> size_list;
    private javax.swing.JList<String> style_list;
    // End of variables declaration//GEN-END:variables
}
