/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intercode;

import static intercode.Registerform.username;
import java.awt.event.KeyEvent;
import java.io.DataInputStream;
import java.io.InputStream;
import java.net.Socket;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author amank
 */
public class Login_form extends javax.swing.JFrame {

    /**
     * Creates new form Login_form
     */
    public Login_form() {
        initComponents();
    }
    
    
    static 
    {
        Thread t = new Thread(new Connect_Client_Login());
        t.start();
        
    }
    
    static String username="";
    static String password="";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        usernamefield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        passfield = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 250, 500, 470));

        jPanel2.setBackground(new java.awt.Color(255, 102, 153));
        jPanel2.setLayout(null);

        usernamefield.setBackground(new java.awt.Color(204, 204, 204));
        usernamefield.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel2.add(usernamefield);
        usernamefield.setBounds(260, 160, 183, 33);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(100, 160, 112, 33);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(100, 220, 124, 44);

        passfield.setBackground(new java.awt.Color(204, 204, 204));
        passfield.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        passfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passfieldKeyPressed(evt);
            }
        });
        jPanel2.add(passfield);
        passfield.setBounds(260, 230, 183, 33);

        login.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        login.setForeground(new java.awt.Color(0, 0, 255));
        login.setText("Log in");
        login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 255), 2, true));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel2.add(login);
        login.setBounds(290, 320, 120, 40);

        cancel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 51, 51));
        cancel.setText("Cancel");
        cancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 255), 2, true));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel2.add(cancel);
        cancel.setBounds(110, 320, 120, 40);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create an account");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1);
        jLabel1.setBounds(360, 380, 150, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("___________________");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(360, 390, 140, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 153));
        jLabel7.setText("Login Form");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(60, 50, 264, 63);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intercode/ak.jpeg"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 530, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

         PreparedStatement ps;
         ResultSet rs;
         
         username = usernamefield.getText();
         password = String.valueOf(passfield.getPassword());
         
         String query = "SELECT * FROM `information` WHERE `u_username` =? AND `u_pass` =?";
         
         try {
            
             ps = MyConnection.getConnection().prepareStatement(query);
             
            ps.setString(1,username);
            ps.setString(2,password);
            
            rs = ps.executeQuery();
            
             
            
            if(rs.next())
            {
                //JOptionPane.showMessageDialog(null, "Succesfully Logged in");
              /*  this.dispose();
                
                Coding cd = new Coding();
                cd.setVisible(true);
                */
                
                
                
                
                
                
                Thread t = new Thread(new Open_coding());
                t.start();
                
                Coding cd = new Coding();
                cd.setVisible(true);
                this.dispose();
          
            }
            else{
                
                JOptionPane.showMessageDialog(null, "Password or username is incorrect");
                
            }
            
            
             
        } catch (Exception e) {
        }
         
         
        
         
    }//GEN-LAST:event_loginActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        Registerform rg = new Registerform();
        rg.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cancelActionPerformed

    private void passfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passfieldKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            
             PreparedStatement ps;
         ResultSet rs;
         
         username = usernamefield.getText();
         password = String.valueOf(passfield.getPassword());
         
         String query = "SELECT * FROM `information` WHERE `u_username` =? AND `u_pass` =?";
         
         try {
            
             ps = MyConnection.getConnection().prepareStatement(query);
             
            ps.setString(1,username);
            ps.setString(2,password);
            
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                //JOptionPane.showMessageDialog(null, "Succesfully Logged in");
              /*  this.dispose();
                
                Coding cd = new Coding();
                cd.setVisible(true);
                */
                
                
                
                
                
                
                Thread t = new Thread(new Open_coding());
                t.start();
                
                Coding cd = new Coding();
                cd.setVisible(true);
                this.dispose();
          
            }
            else{
                
                JOptionPane.showMessageDialog(null, "Password or username is incorrect");
                
            }
             
        } catch (Exception e) {
        }
         
         
            
        }
        
    }//GEN-LAST:event_passfieldKeyPressed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login;
    public static javax.swing.JPasswordField passfield;
    public static javax.swing.JTextField usernamefield;
    // End of variables declaration//GEN-END:variables
}
