/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intercode;

import javax.swing.JOptionPane;
//import org.w3c.dom.xpath.XPathEvaluator;

/**
 *
 * @author amank
 */
public class Path extends javax.swing.JFrame {

    /**
     * Creates new form Path
     */
    public Path() {
        initComponents();
    }
    
    static String Pathval  ="";
    static  String filen ="";
    
    static  String getPath()
    {
        return Pathval;
    }
    
    static  String getFileName()
    {
        return filen;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        filename = new javax.swing.JTextField();
        path = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 300, 500, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("File Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 130, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setText("Path");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 130, 50));

        filename.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(filename, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 220, 50));

        path.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(path, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 220, 50));

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 97, 33));

        jLabel3.setBackground(new java.awt.Color(153, 255, 153));
        jLabel3.setForeground(new java.awt.Color(153, 255, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intercode/background.jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(path.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Give the path.");
            return;
        }
        
        else if(filename.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Give the filename with extension.");
            return;
        }
        
        else
        {
            
            Pathval = path.getText();
            filen = filename.getText();
            
            
            this.dispose();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField filename;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JTextField path;
    // End of variables declaration//GEN-END:variables
}
