/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intercode;

import static java.lang.System.exit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.regex.Matcher; 
import java.util.regex.Pattern;
/**
 *
 * @author amank
 */
public class Registerform extends javax.swing.JFrame {

    /**
     * Creates new form Register_form
     */
    public Registerform() {
        initComponents();
    }
    
    static String fname="";
    static String lname="";
    static String username="";
    static String password="";
    static String repassword="";
    static String email="";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernamefield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fnamefield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mailfield = new javax.swing.JTextField();
        lnamefield = new javax.swing.JTextField();
        repassfield = new javax.swing.JPasswordField();
        passfield = new javax.swing.JPasswordField();
        register = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 200, 516, 624));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 153));
        jLabel7.setText("Registration Form");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 20, 380, 63);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("__________");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(420, 40, 80, 20);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("<<Log in");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(420, 30, 80, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intercode/ak.jpeg"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 540, 630);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 80));

        jPanel2.setBackground(new java.awt.Color(255, 102, 153));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Name");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(76, 54, 112, 33);

        usernamefield.setBackground(new java.awt.Color(204, 204, 204));
        usernamefield.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel2.add(usernamefield);
        usernamefield.setBounds(248, 193, 183, 33);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(76, 192, 112, 33);

        fnamefield.setBackground(new java.awt.Color(204, 204, 204));
        fnamefield.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel2.add(fnamefield);
        fnamefield.setBounds(248, 53, 183, 34);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(80, 120, 112, 35);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Re-enter Password");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(50, 320, 170, 45);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("email id");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(70, 385, 130, 41);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(70, 260, 124, 44);

        mailfield.setBackground(new java.awt.Color(204, 204, 204));
        mailfield.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel2.add(mailfield);
        mailfield.setBounds(248, 390, 183, 33);

        lnamefield.setBackground(new java.awt.Color(204, 204, 204));
        lnamefield.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel2.add(lnamefield);
        lnamefield.setBounds(248, 119, 183, 33);

        repassfield.setBackground(new java.awt.Color(204, 204, 204));
        repassfield.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(repassfield);
        repassfield.setBounds(250, 320, 183, 34);

        passfield.setBackground(new java.awt.Color(204, 204, 204));
        passfield.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(passfield);
        passfield.setBounds(250, 260, 183, 33);

        register.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        register.setForeground(new java.awt.Color(51, 0, 204));
        register.setText("Register");
        register.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 255), 2, true));
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel2.add(register);
        register.setBounds(290, 470, 120, 40);

        cancel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 0, 0));
        cancel.setText("Cancel");
        cancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 255), 2, true));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel2.add(cancel);
        cancel.setBounds(110, 470, 120, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intercode/ak.jpeg"))); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(-2, -84, 540, 650);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 520, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
      
        System.exit(0);
    }//GEN-LAST:event_cancelActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        
        fname = fnamefield.getText();
        lname = lnamefield.getText();
        username = usernamefield.getText();
        
        password = String.valueOf(passfield.getPassword());
        repassword = String.valueOf(repassfield.getPassword());
        
        email = mailfield.getText();
        int count=0;
        
        if(!username.equals(""))
            {
                count++;
            }
            else{
                
                JOptionPane.showMessageDialog(null, "Enter username");
                return; 
            }
            
        if(check(username))
        {
            JOptionPane.showMessageDialog(null, "This username already exist");
            return;
        }
        else{
            count++;
        }
            
            if(password.length()>=8)
            {
                
               count++;
            }
            
            else{
                JOptionPane.showMessageDialog(null, "Password must have atleast 8 charachters.");
                return;
            }
            
            if(password.equals(repassword))
            {
                count++;
            }
            
            else{
                JOptionPane.showMessageDialog(null, "Password doesn't match");
                return;
            }
            
            if(!email.equals(""))
            {
                
                if (isValid(email)) 
                {
                    System.out.print("Yes"); 
                
                 count++;
                }
                
                else
                {
                 System.out.print("No");
                 JOptionPane.showMessageDialog(null, "Enter valid email id");
                 return;
                } 
                
                
               
            }
            
           else
            {
                
                JOptionPane.showMessageDialog(null, "Enter valid email id");
                return;
            }
            System.out.println(count);
        
        PreparedStatement ps ;
        String query ="INSERT INTO `information`(`u_fname`, `u_lname`, `u_username`, `u_pass`, `u_email`) VALUES (?,?,?,?,?)";
        
         if(count ==5)
        {
        try {
            
            ps = MyConnection.getConnection().prepareStatement(query);
            
            ps.setString(1, fname);
            ps.setString(2, lname);
            ps.setString(3, username);
            ps.setString(4, password);
            ps.setString(5, email);
            
           fnamefield.setText("");
           lnamefield.setText("");
           usernamefield.setText("");
           passfield.setText("");
           repassfield.setText("");
           mailfield.setText("");
            
            
            if(ps.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null, "User is added");
            }
            
            
            
        } catch (Exception e) {
        }
        
    }
            
    }//GEN-LAST:event_registerActionPerformed

    
    public static boolean isValid(String email) 
    { 
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+ 
                            "[a-zA-Z0-9_+&*-]+)*@" + 
                            "(?:[a-zA-Z0-9-]+\\.)+[a-z" + 
                            "A-Z]{2,7}$"; 
                              
        Pattern pat = Pattern.compile(emailRegex); 
        if (email == null) 
            return false; 
        return pat.matcher(email).matches(); 
    } 
    
    
    boolean check(String name)
    {
        PreparedStatement ps ;
        ResultSet rs;
        boolean checker = false;
        
        String query = "SELECT * FROM `information` WHERE `u_username` =?";
        
         try {
            
             ps = MyConnection.getConnection().prepareStatement(query);
             
            ps.setString(1,name);
            
            
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                checker = true;
                
            }
           
             
        } catch (Exception e) {
        }
         
        return checker;
        
    }
    
    
    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked

        Login_form rg = new Login_form();
        rg.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    public static javax.swing.JTextField fnamefield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JTextField lnamefield;
    private javax.swing.JTextField mailfield;
    public static javax.swing.JPasswordField passfield;
    private javax.swing.JButton register;
    public static javax.swing.JPasswordField repassfield;
    public static javax.swing.JTextField usernamefield;
    // End of variables declaration//GEN-END:variables
}
